# Generated by Django 4.2.3 on 2023-07-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='images_url',
            field=models.TextField(blank=True, default='', help_text='should split by "|" ', null=True),
        ),
    ]
