# Generated by Django 4.2.3 on 2023-08-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_sku_alter_music_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
